language: node_js
node_js: "6.9.2"
branches:
  only:
  - master
  - develop
notifications:  
  email:
    recipients:
    - e.arranz@alumnos.upm.es
before_script:
- npm install -g @angular/cli@1.0.0
- npm install -g phantomjs
script:
- ng test --watch false